from dataclasses import dataclass


@dataclass(frozen=True)
class NodeDefinition:
    node_type: str
    title: str
    category: str
    inputs: list[dict[str, str]]
    outputs: list[dict[str, str]]
    widgets: list[str | int | bool]


def default_node_catalog() -> dict[str, NodeDefinition]:
    return {
        "SampleMetadataValidatorNode": NodeDefinition("SampleMetadataValidatorNode", "Validate Sample Metadata", "ComfyBIO/Input", [], [{"name": "sample_metadata_csv", "type": "STRING"}], ["harness/examples/fixtures/quickstart", "harness/examples/fixtures/quickstart/sample_metadata.csv", ""]),
        "FastpQCNode": NodeDefinition("FastpQCNode", "FASTQ QC", "ComfyBIO/QC", [{"name": "fastq_pair", "type": "STRING"}], [{"name": "fastp_qc_json", "type": "STRING"}], ["harness/examples/fixtures/quickstart", "harness/examples/fixtures/quickstart/sample_metadata.csv", "harness/examples/runs/quickstart/qc", 2, ""]),
        "FastpTrimNode": NodeDefinition("FastpTrimNode", "Optional FASTQ Trimming", "ComfyBIO/QC", [{"name": "fastp_qc_json", "type": "STRING"}], [{"name": "trimmed_fastq_dir", "type": "STRING"}], ["harness/examples/fixtures/quickstart", "harness/examples/fixtures/quickstart/sample_metadata.csv", "harness/examples/runs/quickstart/trimmed", 2, "--length_required 1"]),
        "SalmonIndexNode": NodeDefinition("SalmonIndexNode", "Salmon Index", "ComfyBIO/Quantification", [{"name": "transcriptome_fasta_path", "type": "STRING"}], [{"name": "salmon_index_dir", "type": "STRING"}], ["harness/examples/fixtures/quickstart/toy_transcriptome.fasta", "harness/examples/runs/quickstart/salmon_index", 2, "-k 7"]),
        "SalmonQuantNode": NodeDefinition("SalmonQuantNode", "Salmon Quant", "ComfyBIO/Quantification", [{"name": "salmon_index_dir", "type": "STRING"}], [{"name": "salmon_quant_dir", "type": "STRING"}], ["harness/examples/runs/quickstart/salmon_index", "harness/examples/fixtures/quickstart", "harness/examples/fixtures/quickstart/sample_metadata.csv", "harness/examples/runs/quickstart/salmon_quant", "A", 2, ""]),
        "TximportNode": NodeDefinition("TximportNode", "Import Counts For DESeq2", "ComfyBIO/Differential Expression", [{"name": "salmon_quant_dir_path", "type": "STRING"}], [{"name": "deseq2_count_matrix", "type": "STRING"}], ["harness/examples/runs/quickstart/salmon_quant", "harness/examples/fixtures/quickstart/sample_metadata.csv", "harness/examples/runs/quickstart/deseq2/count_matrix.csv", ""]),
        "DESeq2AnalysisNode": NodeDefinition("DESeq2AnalysisNode", "DESeq2 Analysis", "ComfyBIO/Differential Expression", [{"name": "deseq2_count_matrix", "type": "STRING"}], [{"name": "deseq2_results_table", "type": "STRING"}], ["harness/examples/runs/quickstart/deseq2/count_matrix.csv", "harness/examples/fixtures/quickstart/sample_metadata.csv", "harness/examples/runs/quickstart/deseq2/results.csv", "~ condition", ""]),
        "DESeq2VisualizationNode": NodeDefinition("DESeq2VisualizationNode", "DESeq2 Visualization", "ComfyBIO/Visualization", [{"name": "deseq2_results_table", "type": "STRING"}], [{"name": "plot_dir", "type": "STRING"}, {"name": "preview_plot", "type": "IMAGE"}], ["harness/examples/runs/quickstart/deseq2/count_matrix.csv", "harness/examples/runs/quickstart/deseq2/results.csv", "harness/examples/runs/quickstart/plots", "pca,ma,volcano,heatmap"]),
        "TenxCountNode": NodeDefinition("TenxCountNode", "10x Count Matrix Generation", "ComfyBIO/scRNA-seq", [], [{"name": "filtered_feature_bc_matrix", "type": "STRING"}], ["harness/examples/fixtures/scrna/fastqs", "sample_001", "harness/examples/fixtures/scrna/cellranger_reference", "harness/examples/runs/scrna/cellranger_count/filtered_feature_bc_matrix", 8, ""]),
        "ScanpyQCNode": NodeDefinition("ScanpyQCNode", "Scanpy Cell QC", "ComfyBIO/scRNA-seq", [{"name": "filtered_feature_bc_matrix", "type": "STRING"}], [{"name": "qc_h5ad", "type": "STRING"}], ["harness/examples/runs/scrna/cellranger_count/filtered_feature_bc_matrix", "harness/examples/runs/scrna/scanpy/qc.h5ad", 200, 20, ""]),
        "ScanpyNormalizeNode": NodeDefinition("ScanpyNormalizeNode", "Scanpy Normalize", "ComfyBIO/scRNA-seq", [{"name": "qc_h5ad", "type": "STRING"}], [{"name": "normalized_h5ad", "type": "STRING"}], ["harness/examples/runs/scrna/scanpy/qc.h5ad", "harness/examples/runs/scrna/scanpy/normalized.h5ad", 10000, ""]),
        "ScanpyClusterNode": NodeDefinition("ScanpyClusterNode", "Scanpy Cluster", "ComfyBIO/scRNA-seq", [{"name": "normalized_h5ad", "type": "STRING"}], [{"name": "clustered_h5ad", "type": "STRING"}], ["harness/examples/runs/scrna/scanpy/normalized.h5ad", "harness/examples/runs/scrna/scanpy/clustered.h5ad", 30, 1, ""]),
        "ScanpyMarkerGenesNode": NodeDefinition("ScanpyMarkerGenesNode", "Scanpy Marker Genes", "ComfyBIO/scRNA-seq", [{"name": "clustered_h5ad", "type": "STRING"}], [{"name": "marker_genes_csv", "type": "STRING"}], ["harness/examples/runs/scrna/scanpy/clustered.h5ad", "harness/examples/runs/scrna/scanpy/markers.csv", "leiden", "wilcoxon", ""]),
        "ScRNAVisualizationNode": NodeDefinition("ScRNAVisualizationNode", "scRNA Visualization", "ComfyBIO/scRNA-seq", [{"name": "marker_genes_csv", "type": "STRING"}], [{"name": "plot_dir", "type": "STRING"}, {"name": "preview_plot", "type": "IMAGE"}], ["harness/examples/runs/scrna/scanpy/clustered.h5ad", "harness/examples/runs/scrna/scanpy/markers.csv", "harness/examples/runs/scrna/scanpy/plots", "umap,clusters,marker_dotplot"]),
        "ScRNAReportNode": NodeDefinition("ScRNAReportNode", "scRNA Report", "ComfyBIO/scRNA-seq", [{"name": "plot_dir_path", "type": "STRING"}], [{"name": "report_markdown", "type": "STRING"}], ["harness/examples/runs/scrna/scanpy/clustered.h5ad", "harness/examples/runs/scrna/scanpy/markers.csv", "harness/examples/runs/scrna/scanpy/plots", "harness/examples/runs/scrna/report/scrna_report.md", ""]),
        "ComfyBIOReportNode": NodeDefinition("ComfyBIOReportNode", "ComfyBIO Report", "ComfyBIO/Reporting", [{"name": "plot_dir_path", "type": "STRING"}], [{"name": "report_markdown", "type": "STRING"}], ["harness/examples/runs/quickstart/deseq2/results.csv", "harness/examples/runs/quickstart/plots", "harness/examples/runs/quickstart/report/comfybio_report.md", ""]),
        "VariantInputValidatorNode": NodeDefinition("VariantInputValidatorNode", "Validate Variant Inputs", "ComfyBIO/Input", [], [{"name": "sample_metadata_csv", "type": "STRING"}], ["harness/examples/fixtures/variant", "harness/examples/fixtures/variant/reference.fasta", "harness/examples/fixtures/variant/sample_metadata.csv", ""]),
        "BwaMem2IndexNode": NodeDefinition("BwaMem2IndexNode", "bwa-mem2 Index", "ComfyBIO/Alignment", [{"name": "sample_metadata_csv", "type": "STRING"}], [{"name": "reference_fasta_indexed", "type": "STRING"}], ["harness/examples/fixtures/variant/reference.fasta", ""]),
        "BwaMem2AlignNode": NodeDefinition("BwaMem2AlignNode", "bwa-mem2 Align", "ComfyBIO/Alignment", [{"name": "reference_fasta_indexed", "type": "STRING"}], [{"name": "sorted_bam_dir", "type": "STRING"}], ["harness/examples/fixtures/variant", "harness/examples/fixtures/variant/reference.fasta", "harness/examples/fixtures/variant/sample_metadata.csv", "harness/examples/runs/variant/aligned", 4, ""]),
        "MarkDuplicatesNode": NodeDefinition("MarkDuplicatesNode", "Mark Duplicates", "ComfyBIO/Alignment", [{"name": "sorted_bam_dir", "type": "STRING"}], [{"name": "dedup_bam_dir", "type": "STRING"}], ["harness/examples/runs/variant/aligned", "harness/examples/runs/variant/dedup", 4, ""]),
        "BcftoolsCallNode": NodeDefinition("BcftoolsCallNode", "bcftools Call", "ComfyBIO/Variant Calling", [{"name": "dedup_bam_dir", "type": "STRING"}], [{"name": "raw_vcf_dir", "type": "STRING"}], ["harness/examples/runs/variant/dedup", "harness/examples/fixtures/variant/reference.fasta", "harness/examples/runs/variant/calls", ""]),
        "BcftoolsFilterNode": NodeDefinition("BcftoolsFilterNode", "bcftools Filter", "ComfyBIO/Variant Calling", [{"name": "raw_vcf_dir", "type": "STRING"}], [{"name": "filtered_vcf_dir", "type": "STRING"}], ["harness/examples/runs/variant/calls", "harness/examples/runs/variant/filtered", "QUAL<20 || DP<10", ""]),
        "VariantVisualizationNode": NodeDefinition("VariantVisualizationNode", "Variant Visualization", "ComfyBIO/Visualization", [{"name": "filtered_vcf_dir", "type": "STRING"}], [{"name": "plot_dir", "type": "STRING"}, {"name": "preview_plot", "type": "IMAGE"}], ["harness/examples/runs/variant/filtered", "harness/examples/runs/variant/plots", ""]),
        "VariantReportNode": NodeDefinition("VariantReportNode", "Variant Report", "ComfyBIO/Reporting", [{"name": "plot_dir_path", "type": "STRING"}], [{"name": "report_markdown", "type": "STRING"}], ["harness/examples/runs/variant/filtered", "harness/examples/runs/variant/plots", "harness/examples/runs/variant/report/variant_report.md", ""]),
        "AtacInputValidatorNode": NodeDefinition("AtacInputValidatorNode", "Validate ATAC-seq Inputs", "ComfyBIO/Input", [], [{"name": "sample_metadata_csv", "type": "STRING"}], ["harness/examples/fixtures/atac", "harness/examples/fixtures/atac/reference.fasta", "harness/examples/fixtures/atac/sample_metadata.csv", ""]),
        "AtacFastpTrimNode": NodeDefinition("AtacFastpTrimNode", "fastp Trim (ATAC-seq)", "ComfyBIO/QC", [{"name": "sample_metadata_csv", "type": "STRING"}], [{"name": "trimmed_fastq_dir", "type": "STRING"}], ["harness/examples/fixtures/atac", "harness/examples/fixtures/atac/sample_metadata.csv", "harness/examples/runs/atac/trimmed", 2, ""]),
        "AtacBwaMem2IndexNode": NodeDefinition("AtacBwaMem2IndexNode", "bwa-mem2 Index (ATAC-seq)", "ComfyBIO/Alignment", [{"name": "trimmed_fastq_dir", "type": "STRING"}], [{"name": "reference_fasta_indexed", "type": "STRING"}], ["harness/examples/fixtures/atac/reference.fasta", ""]),
        "AtacBwaMem2AlignNode": NodeDefinition("AtacBwaMem2AlignNode", "bwa-mem2 Align (ATAC-seq)", "ComfyBIO/Alignment", [{"name": "reference_fasta_indexed", "type": "STRING"}], [{"name": "sorted_bam_dir", "type": "STRING"}], ["harness/examples/fixtures/atac", "harness/examples/fixtures/atac/reference.fasta", "harness/examples/fixtures/atac/sample_metadata.csv", "harness/examples/runs/atac/trimmed", "harness/examples/runs/atac/aligned", 4, ""]),
        "AtacMarkDuplicatesNode": NodeDefinition("AtacMarkDuplicatesNode", "Mark Duplicates (ATAC-seq)", "ComfyBIO/Alignment", [{"name": "sorted_bam_dir", "type": "STRING"}], [{"name": "dedup_bam_dir", "type": "STRING"}], ["harness/examples/runs/atac/aligned", "harness/examples/runs/atac/dedup", 4, ""]),
        "AtacQualityFilterNode": NodeDefinition("AtacQualityFilterNode", "ATAC-seq Quality Filter", "ComfyBIO/QC", [{"name": "dedup_bam_dir", "type": "STRING"}], [{"name": "filtered_bam_dir", "type": "STRING"}], ["harness/examples/runs/atac/dedup", "harness/examples/runs/atac/filtered", 30, "1804", "chrM", ""]),
        "Macs3PeakCallingNode": NodeDefinition("Macs3PeakCallingNode", "MACS3 Peak Calling", "ComfyBIO/Peak Calling", [{"name": "filtered_bam_dir", "type": "STRING"}], [{"name": "peaks_dir", "type": "STRING"}], ["harness/examples/runs/atac/filtered", "harness/examples/runs/atac/peaks", "hs", ""]),
        "AtacPeakVisualizationNode": NodeDefinition("AtacPeakVisualizationNode", "ATAC-seq Peak Visualization", "ComfyBIO/Visualization", [{"name": "peaks_dir", "type": "STRING"}], [{"name": "plot_dir", "type": "STRING"}, {"name": "preview_plot", "type": "IMAGE"}], ["harness/examples/runs/atac/peaks", "harness/examples/runs/atac/plots", ""]),
        "AtacReportNode": NodeDefinition("AtacReportNode", "ATAC-seq Report", "ComfyBIO/Reporting", [{"name": "plot_dir_path", "type": "STRING"}], [{"name": "report_markdown", "type": "STRING"}], ["harness/examples/runs/atac/peaks", "harness/examples/runs/atac/plots", "harness/examples/runs/atac/report/atac_report.md", ""]),
        "MetagenomeInputValidatorNode": NodeDefinition("MetagenomeInputValidatorNode", "Validate Metagenome Inputs", "ComfyBIO/Input", [], [{"name": "sample_metadata_csv", "type": "STRING"}], ["harness/examples/fixtures/metagenome", "harness/examples/fixtures/metagenome/kraken2_db", "harness/examples/fixtures/metagenome/sample_metadata.csv", ""]),
        "MetagenomeFastpTrimNode": NodeDefinition("MetagenomeFastpTrimNode", "fastp Trim (Metagenome)", "ComfyBIO/QC", [{"name": "sample_metadata_csv", "type": "STRING"}], [{"name": "trimmed_fastq_dir", "type": "STRING"}], ["harness/examples/fixtures/metagenome", "harness/examples/fixtures/metagenome/sample_metadata.csv", "harness/examples/runs/metagenome/trimmed", 2, ""]),
        "Kraken2ClassifyNode": NodeDefinition("Kraken2ClassifyNode", "Kraken2 Classify", "ComfyBIO/Taxonomic Classification", [{"name": "trimmed_fastq_dir", "type": "STRING"}], [{"name": "kraken2_output_dir", "type": "STRING"}], ["harness/examples/fixtures/metagenome", "harness/examples/fixtures/metagenome/sample_metadata.csv", "harness/examples/runs/metagenome/trimmed", "harness/examples/fixtures/metagenome/kraken2_db", "harness/examples/runs/metagenome/kraken2", 4, 0.1, ""]),
        "BrackenAbundanceNode": NodeDefinition("BrackenAbundanceNode", "Bracken Abundance", "ComfyBIO/Taxonomic Classification", [{"name": "kraken2_output_dir", "type": "STRING"}], [{"name": "bracken_dir", "type": "STRING"}], ["harness/examples/runs/metagenome/kraken2", "harness/examples/fixtures/metagenome/kraken2_db", "harness/examples/runs/metagenome/bracken", 100, "S", 10, ""]),
        "MetagenomeVisualizationNode": NodeDefinition("MetagenomeVisualizationNode", "Metagenome Visualization", "ComfyBIO/Visualization", [{"name": "bracken_dir", "type": "STRING"}], [{"name": "plot_dir", "type": "STRING"}, {"name": "preview_plot", "type": "IMAGE"}], ["harness/examples/runs/metagenome/bracken", "harness/examples/runs/metagenome/plots", ""]),
        "MetagenomeReportNode": NodeDefinition("MetagenomeReportNode", "Metagenome Report", "ComfyBIO/Reporting", [{"name": "plot_dir_path", "type": "STRING"}], [{"name": "report_markdown", "type": "STRING"}], ["harness/examples/runs/metagenome/bracken", "harness/examples/runs/metagenome/plots", "harness/examples/runs/metagenome/report/metagenome_report.md", ""]),
    }
