"""Auto-generated by bioflow_harness.autogen.node_synthesizer. Unreviewed LLM output — verify before trusting in production."""

from pathlib import Path

from ..execution import resolve_runner, load_preview_tensor
from ..ref_nodes import _BaseComfyBIONode
from . import bulk_rnaseq_deg_stage_commands

AUTOGEN_NODE_CLASSES = ["FastpNode", "SalmonNode", "Deseq2Node", "EnhancedvolcanoNode"]


class FastpNode(_BaseComfyBIONode):
    CATEGORY = "ComfyBIO/Autogen"
    RETURN_NAMES = ("trimmed_fastq",)

    @classmethod
    def INPUT_TYPES(cls) -> dict:
        return {
            "required": {
                "raw_fastq": cls._upstream_input(),
                "output_dir": cls._string_input("trimmed_fastq"),
                "extra_command": cls._extra_command_input(),
            }
        }

    def run(self, raw_fastq, output_dir, extra_command="", runner=None) -> tuple[str]:
        runner = resolve_runner(runner)
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)
        runner.run(bulk_rnaseq_deg_stage_commands.fastp_argv(raw_fastq, out, extra_command), out)
        return (str(out),)


class SalmonNode(_BaseComfyBIONode):
    CATEGORY = "ComfyBIO/Autogen"
    RETURN_NAMES = ("quant_sf",)

    @classmethod
    def INPUT_TYPES(cls) -> dict:
        return {
            "required": {
                "trimmed_fastq": cls._upstream_input(),
                "output_dir": cls._string_input("quant_sf"),
                "extra_command": cls._extra_command_input(),
            }
        }

    def run(self, trimmed_fastq, output_dir, extra_command="", runner=None) -> tuple[str]:
        runner = resolve_runner(runner)
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)
        runner.run(bulk_rnaseq_deg_stage_commands.salmon_argv(trimmed_fastq, out, extra_command), out)
        return (str(out),)


class Deseq2Node(_BaseComfyBIONode):
    CATEGORY = "ComfyBIO/Autogen"
    RETURN_NAMES = ("deg_table",)

    @classmethod
    def INPUT_TYPES(cls) -> dict:
        return {
            "required": {
                "quant_sf": cls._upstream_input(),
                "output_dir": cls._string_input("deg_table"),
                "extra_command": cls._extra_command_input(),
            }
        }

    def run(self, quant_sf, output_dir, extra_command="", runner=None) -> tuple[str]:
        runner = resolve_runner(runner)
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)
        runner.run(bulk_rnaseq_deg_stage_commands.deseq2_argv(quant_sf, out, extra_command), out)
        return (str(out),)


class EnhancedvolcanoNode(_BaseComfyBIONode):
    CATEGORY = "ComfyBIO/Visualization"
    RETURN_TYPES = ("STRING", "IMAGE")
    RETURN_NAMES = ("volcano_plot_png", "preview_plot")

    @classmethod
    def INPUT_TYPES(cls) -> dict:
        return {
            "required": {
                "deg_table": cls._upstream_input(),
                "output_dir": cls._string_input("volcano_plot_png"),
                "extra_command": cls._extra_command_input(),
            }
        }

    def run(self, deg_table, output_dir, extra_command="", runner=None, preview_loader=None) -> tuple[str, object]:
        runner = resolve_runner(runner)
        loader = preview_loader if preview_loader is not None else load_preview_tensor
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)
        runner.run(bulk_rnaseq_deg_stage_commands.enhancedvolcano_argv(deg_table, out, extra_command), out)
        return (str(out), loader(out / "preview.png"))
