"""Auto-generated by bioflow_harness.autogen.node_synthesizer. Unreviewed LLM output — verify before trusting in production."""

from pathlib import Path

from bioflow_harness.runtime.command_runner import conda_command, parse_extra_command_tokens

ENV_NAME = "rnaseq_deg"


def _extra(extra_command: str) -> list[str]:
    return parse_extra_command_tokens(extra_command) if extra_command else []


def fastp_argv(input_path, output_dir, extra_command: str = "") -> list[str]:
    static_args = ["--detect_adapter_for_pe"]
    return conda_command(
        ENV_NAME, "fastp", *static_args,
        str(input_path), "-o", str(output_dir),
        *_extra(extra_command),
    )

def salmon_argv(input_path, output_dir, extra_command: str = "") -> list[str]:
    static_args = ["--libType", "A", "--validateMappings", "--gcBias"]
    return conda_command(
        ENV_NAME, "salmon", *static_args,
        str(input_path), "-o", str(output_dir),
        *_extra(extra_command),
    )

def deseq2_argv(input_path, output_dir, extra_command: str = "") -> list[str]:
    static_args = ["--alpha", "0.05"]
    return conda_command(
        ENV_NAME, "Rscript", *static_args,
        str(input_path), "-o", str(output_dir),
        *_extra(extra_command),
    )

def enhancedvolcano_argv(input_path, output_dir, extra_command: str = "") -> list[str]:
    static_args = ["--pCutoff", "0.05", "--FCcutoff", "1.0"]
    return conda_command(
        ENV_NAME, "Rscript", *static_args,
        str(input_path), "-o", str(output_dir),
        *_extra(extra_command),
    )
