"""Auto-generated by bioflow_harness.autogen.node_synthesizer. Unreviewed LLM output — verify before trusting in production."""

from pathlib import Path

from ..execution import resolve_runner, load_preview_tensor
from ..ref_nodes import _BaseComfyBIONode
from . import chip_seq_stage_commands

AUTOGEN_NODE_CLASSES = ["FastpNode", "Bowtie2Node", "SamtoolsNode", "Macs2Node", "DeeptoolsPlotheatmapNode"]


class FastpNode(_BaseComfyBIONode):
    CATEGORY = "ComfyBIO/Autogen"
    RETURN_NAMES = ("trimmed_fastq",)

    @classmethod
    def INPUT_TYPES(cls) -> dict:
        return {
            "required": {
                "fastq": cls._upstream_input(),
                "output_dir": cls._string_input("trimmed_fastq"),
                "extra_command": cls._extra_command_input(),
            }
        }

    def run(self, fastq, output_dir, extra_command="", runner=None) -> tuple[str]:
        runner = resolve_runner(runner)
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)
        runner.run(chip_seq_stage_commands.fastp_argv(fastq, out, extra_command), out)
        return (str(out),)


class Bowtie2Node(_BaseComfyBIONode):
    CATEGORY = "ComfyBIO/Autogen"
    RETURN_NAMES = ("sam_alignment",)

    @classmethod
    def INPUT_TYPES(cls) -> dict:
        return {
            "required": {
                "trimmed_fastq": cls._upstream_input(),
                "output_dir": cls._string_input("sam_alignment"),
                "extra_command": cls._extra_command_input(),
            }
        }

    def run(self, trimmed_fastq, output_dir, extra_command="", runner=None) -> tuple[str]:
        runner = resolve_runner(runner)
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)
        runner.run(chip_seq_stage_commands.bowtie2_argv(trimmed_fastq, out, extra_command), out)
        return (str(out),)


class SamtoolsNode(_BaseComfyBIONode):
    CATEGORY = "ComfyBIO/Autogen"
    RETURN_NAMES = ("sorted_bam",)

    @classmethod
    def INPUT_TYPES(cls) -> dict:
        return {
            "required": {
                "sam_alignment": cls._upstream_input(),
                "output_dir": cls._string_input("sorted_bam"),
                "extra_command": cls._extra_command_input(),
            }
        }

    def run(self, sam_alignment, output_dir, extra_command="", runner=None) -> tuple[str]:
        runner = resolve_runner(runner)
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)
        runner.run(chip_seq_stage_commands.samtools_argv(sam_alignment, out, extra_command), out)
        return (str(out),)


class Macs2Node(_BaseComfyBIONode):
    CATEGORY = "ComfyBIO/Autogen"
    RETURN_NAMES = ("peak_calls",)

    @classmethod
    def INPUT_TYPES(cls) -> dict:
        return {
            "required": {
                "sorted_bam": cls._upstream_input(),
                "output_dir": cls._string_input("peak_calls"),
                "extra_command": cls._extra_command_input(),
            }
        }

    def run(self, sorted_bam, output_dir, extra_command="", runner=None) -> tuple[str]:
        runner = resolve_runner(runner)
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)
        runner.run(chip_seq_stage_commands.macs2_argv(sorted_bam, out, extra_command), out)
        return (str(out),)


class DeeptoolsPlotheatmapNode(_BaseComfyBIONode):
    CATEGORY = "ComfyBIO/Visualization"
    RETURN_TYPES = ("STRING", "IMAGE")
    RETURN_NAMES = ("visualization_artifacts", "preview_plot")

    @classmethod
    def INPUT_TYPES(cls) -> dict:
        return {
            "required": {
                "bigwig_signal": cls._upstream_input(),
                "output_dir": cls._string_input("visualization_artifacts"),
                "extra_command": cls._extra_command_input(),
            }
        }

    def run(self, bigwig_signal, output_dir, extra_command="", runner=None, preview_loader=None) -> tuple[str, object]:
        runner = resolve_runner(runner)
        loader = preview_loader if preview_loader is not None else load_preview_tensor
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)
        runner.run(chip_seq_stage_commands.deeptools_plotheatmap_argv(bigwig_signal, out, extra_command), out)
        return (str(out), loader(out / "preview.png"))
