"""Auto-generated by bioflow_harness.autogen.node_synthesizer. Unreviewed LLM output — verify before trusting in production."""

from pathlib import Path

from bioflow_harness.runtime.command_runner import conda_command, parse_extra_command_tokens

ENV_NAME = "chipseq_peaks"


def _extra(extra_command: str) -> list[str]:
    return parse_extra_command_tokens(extra_command) if extra_command else []


def fastp_argv(input_path, output_dir, extra_command: str = "") -> list[str]:
    static_args = ["--detect_adapter_for_pe"]
    return conda_command(
        ENV_NAME, "fastp", *static_args,
        str(input_path), "-o", str(output_dir),
        *_extra(extra_command),
    )

def bowtie2_argv(input_path, output_dir, extra_command: str = "") -> list[str]:
    static_args = ["--very-sensitive"]
    return conda_command(
        ENV_NAME, "bowtie2", *static_args,
        str(input_path), "-o", str(output_dir),
        *_extra(extra_command),
    )

def samtools_argv(input_path, output_dir, extra_command: str = "") -> list[str]:
    static_args = ["-q", "30"]
    return conda_command(
        ENV_NAME, "samtools", *static_args,
        str(input_path), "-o", str(output_dir),
        *_extra(extra_command),
    )

def macs2_argv(input_path, output_dir, extra_command: str = "") -> list[str]:
    static_args = ["-g", "hs", "-f", "BAM", "--keep-dup", "all"]
    return conda_command(
        ENV_NAME, "macs2", *static_args,
        str(input_path), "-o", str(output_dir),
        *_extra(extra_command),
    )

def deeptools_plotheatmap_argv(input_path, output_dir, extra_command: str = "") -> list[str]:
    static_args = ["--colorMap", "RdBu_r", "--whatToShow", "plot, heatmap and colorbar"]
    return conda_command(
        ENV_NAME, "plotHeatmap", *static_args,
        str(input_path), "-o", str(output_dir),
        *_extra(extra_command),
    )
