from __future__ import annotations

import ast
import importlib.util
import json
import os
import re
import tempfile
from dataclasses import dataclass
from pathlib import Path

from bioflow_harness.autogen.route_proposal import RouteProposal, StageProposal
from bioflow_harness.comfy.node_catalog import AUTOGEN_NODE_CATALOG_PATH, NodeDefinition
from bioflow_harness.runtime.command_runner import DryRunCommandRunner

_REPO_ROOT = Path(__file__).resolve().parents[4]
NODES_AUTOGEN_DIR = _REPO_ROOT / "nodes" / "autogen"


class NodeSynthesisError(RuntimeError):
    """Raised when generated node/argv-builder code fails a structural safety check."""


def _to_pascal_case(slug: str) -> str:
    return "".join(part.capitalize() for part in re.split(r"[_\-]+", slug) if part)


def _class_name(tool_id: str) -> str:
    return f"{_to_pascal_case(tool_id)}Node"


def _upstream_slot_name(stage: StageProposal) -> str:
    return stage.input_types[0] if stage.input_types else "upstream"


def _output_slot_name(stage: StageProposal) -> str:
    return stage.output_types[0] if stage.output_types else "output_dir"


@dataclass(frozen=True)
class SynthesizedNode:
    class_name: str
    module_name: str
    file_path: Path
    node_definition: NodeDefinition


def _render_stage_commands_module(proposal: RouteProposal) -> str:
    lines = [
        '"""Auto-generated by bioflow_harness.autogen.node_synthesizer. Unreviewed LLM output — verify before trusting in production."""',
        "",
        "from pathlib import Path",
        "",
        "from bioflow_harness.runtime.command_runner import conda_command, parse_extra_command_tokens",
        "",
        f'ENV_NAME = "{proposal.conda_env_name}"',
        "",
        "",
        "def _extra(extra_command: str) -> list[str]:",
        "    return parse_extra_command_tokens(extra_command) if extra_command else []",
        "",
    ]
    for stage in proposal.stages:
        static_args_repr = json.dumps(stage.static_args)
        lines += [
            "",
            f"def {stage.tool_id}_argv(input_path, output_dir, extra_command: str = \"\") -> list[str]:",
            f"    static_args = {static_args_repr}",
            "    return conda_command(",
            f'        ENV_NAME, "{stage.executable}", *static_args,',
            "        str(input_path), \"-o\", str(output_dir),",
            "        *_extra(extra_command),",
            "    )",
        ]
    return "\n".join(lines) + "\n"


def _render_node_class(stage: StageProposal, stage_commands_module: str) -> str:
    class_name = _class_name(stage.tool_id)
    upstream_name = _upstream_slot_name(stage)
    output_name = _output_slot_name(stage)
    if stage.produces_image:
        return f'''

class {class_name}(_BaseComfyBIONode):
    CATEGORY = "ComfyBIO/Visualization"
    RETURN_TYPES = ("STRING", "IMAGE")
    RETURN_NAMES = ("{output_name}", "preview_plot")

    @classmethod
    def INPUT_TYPES(cls) -> dict:
        return {{
            "required": {{
                "{upstream_name}": cls._upstream_input(),
                "output_dir": cls._string_input("{output_name}"),
                "extra_command": cls._extra_command_input(),
            }}
        }}

    def run(self, {upstream_name}, output_dir, extra_command="", runner=None, preview_loader=None) -> tuple[str, object]:
        runner = resolve_runner(runner)
        loader = preview_loader if preview_loader is not None else load_preview_tensor
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)
        runner.run({stage_commands_module}.{stage.tool_id}_argv({upstream_name}, out, extra_command), out)
        return (str(out), loader(out / "preview.png"))
'''
    return f'''

class {class_name}(_BaseComfyBIONode):
    CATEGORY = "ComfyBIO/Autogen"
    RETURN_NAMES = ("{output_name}",)

    @classmethod
    def INPUT_TYPES(cls) -> dict:
        return {{
            "required": {{
                "{upstream_name}": cls._upstream_input(),
                "output_dir": cls._string_input("{output_name}"),
                "extra_command": cls._extra_command_input(),
            }}
        }}

    def run(self, {upstream_name}, output_dir, extra_command="", runner=None) -> tuple[str]:
        runner = resolve_runner(runner)
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)
        runner.run({stage_commands_module}.{stage.tool_id}_argv({upstream_name}, out, extra_command), out)
        return (str(out),)
'''


def _render_nodes_module(proposal: RouteProposal, stage_commands_module: str) -> str:
    class_names = [_class_name(stage.tool_id) for stage in proposal.stages]
    header = [
        '"""Auto-generated by bioflow_harness.autogen.node_synthesizer. Unreviewed LLM output — verify before trusting in production."""',
        "",
        "from pathlib import Path",
        "",
        "from ..execution import resolve_runner, load_preview_tensor",
        "from ..ref_nodes import _BaseComfyBIONode",
        f"from . import {stage_commands_module}",
        "",
        f"AUTOGEN_NODE_CLASSES = {json.dumps(class_names)}",
    ]
    body = "".join(_render_node_class(stage, stage_commands_module) for stage in proposal.stages)
    return "\n".join(header) + "\n" + body


def _node_definition_for(stage: StageProposal) -> NodeDefinition:
    class_name = _class_name(stage.tool_id)
    upstream_name = _upstream_slot_name(stage)
    output_name = _output_slot_name(stage)
    outputs = [{"name": output_name, "type": "STRING"}]
    if stage.produces_image:
        outputs.append({"name": "preview_plot", "type": "IMAGE"})
    return NodeDefinition(
        node_type=class_name,
        title=stage.tool_label,
        category="ComfyBIO/Visualization" if stage.produces_image else "ComfyBIO/Autogen",
        inputs=[{"name": upstream_name, "type": "STRING"}],
        outputs=outputs,
        widgets=[f"{output_name}", ""],
    )


def _write_atomic(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(dir=str(path.parent), prefix=f".{path.name}.", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(content)
        os.replace(tmp_name, path)
    except BaseException:
        if os.path.exists(tmp_name):
            os.remove(tmp_name)
        raise


def _register_autogen_package(nodes_dir: Path) -> None:
    """Register (or repoint) the `nodes.autogen` package in sys.modules so that generated
    modules' package-relative imports (`from . import <stage_commands_module>`) resolve
    against `nodes_dir` — which may be the real repo `nodes/autogen` dir, or an isolated
    temp dir when called from a test."""
    import sys
    import types

    if "nodes" not in sys.modules:
        import nodes  # noqa: F401  (repo-root package; makes `nodes.autogen` resolvable)

    package_name = "nodes.autogen"
    existing = sys.modules.get(package_name)
    if existing is not None and getattr(existing, "__path__", [None])[0] == str(nodes_dir):
        return
    package = types.ModuleType(package_name)
    package.__path__ = [str(nodes_dir)]
    package.__package__ = package_name
    sys.modules[package_name] = package


def _smoke_test_module(module_path: Path, module_import_name: str, proposal: RouteProposal, nodes_dir: Path) -> None:
    _register_autogen_package(nodes_dir)
    spec = importlib.util.spec_from_file_location(module_import_name, module_path)
    if spec is None or spec.loader is None:
        raise NodeSynthesisError(f"Could not load generated module: {module_path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    for stage in proposal.stages:
        node_cls = getattr(module, _class_name(stage.tool_id))
        node = node_cls()
        upstream_name = _upstream_slot_name(stage)
        kwargs = {upstream_name: "dummy_upstream_value", "output_dir": tempfile.mkdtemp(), "runner": DryRunCommandRunner()}
        if stage.produces_image:
            kwargs["preview_loader"] = lambda _path: "fake_image_tensor"
        node.run(**kwargs)


def synthesize(proposal: RouteProposal, *, nodes_dir: Path | None = None, catalog_path: Path | None = None) -> list[SynthesizedNode]:
    """Generate argv-builder + node-class modules for a researched route, validate them
    structurally (syntax check + dry-run smoke test), and append NodeDefinitions to the
    autogen node catalog sidecar. Raises NodeSynthesisError on any structural failure
    (nothing partially-broken is left registered)."""
    nodes_dir = nodes_dir or NODES_AUTOGEN_DIR
    catalog_path = catalog_path or AUTOGEN_NODE_CATALOG_PATH
    stage_commands_module = f"{proposal.domain_slug}_stage_commands"
    nodes_module = f"{proposal.domain_slug}_nodes"

    stage_commands_source = _render_stage_commands_module(proposal)
    nodes_source = _render_nodes_module(proposal, stage_commands_module)

    try:
        ast.parse(stage_commands_source)
        ast.parse(nodes_source)
    except SyntaxError as exc:
        raise NodeSynthesisError(f"Generated code failed syntax check: {exc}") from exc

    init_path = nodes_dir / "__init__.py"
    stage_commands_path = nodes_dir / f"{stage_commands_module}.py"
    nodes_path = nodes_dir / f"{nodes_module}.py"

    if not init_path.exists():
        _write_atomic(init_path, "")
    _write_atomic(stage_commands_path, stage_commands_source)
    _write_atomic(nodes_path, nodes_source)

    try:
        module_import_name = f"nodes.autogen.{nodes_module}"
        _smoke_test_module(nodes_path, module_import_name, proposal, nodes_dir)
    except Exception as exc:
        stage_commands_path.unlink(missing_ok=True)
        nodes_path.unlink(missing_ok=True)
        raise NodeSynthesisError(f"Generated node code failed smoke test: {exc}") from exc

    definitions = [_node_definition_for(stage) for stage in proposal.stages]
    existing = json.loads(catalog_path.read_text(encoding="utf-8")) if catalog_path.exists() else []
    existing_types = {entry["node_type"] for entry in existing}
    new_entries = [
        {
            "node_type": d.node_type,
            "title": d.title,
            "category": d.category,
            "inputs": d.inputs,
            "outputs": d.outputs,
            "widgets": d.widgets,
        }
        for d in definitions
        if d.node_type not in existing_types
    ]
    _write_atomic(catalog_path, json.dumps(existing + new_entries, indent=2) + "\n")

    return [
        SynthesizedNode(
            class_name=_class_name(stage.tool_id),
            module_name=nodes_module,
            file_path=nodes_path,
            node_definition=definition,
        )
        for stage, definition in zip(proposal.stages, definitions)
    ]
